### ISSUE TITLE
Newsletter Forms Need to Be Linked

### ISSUE THREAD

**Issue by bbertucc** [4pt0/4pt0-theme#1]
The Newsletter form needs to be linked to an existing newsletter service. Currently it's linked to http://newsletter.decubing.com/.

**Comment by bbertucc** [comment]
@raphaelgang - Are you using a newsletter service? I'll need the signup form info, so I can integrate it. Thx!

**Comment by raphaelgang** [comment]
We use mailchimp. What information do you need from us?

**Comment by bbertucc** [comment]
@raphaelgang - We'll need the HTML of a signup form. Here's Mailchimp's How-Tod Document: https://kb.mailchimp.com/lists/signup-forms/add-a-signup-form-to-your-website

**Comment by raphaelgang** [comment]
Here's the html
<link
href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet"
type="text/css"><style type="text/css"> #mc_embed_signup{background:#fff;
clear:left; font:14px Helvetica,Arial,sans-serif; } /* Add your own MailChimp
form style overrides in your site stylesheet or in this style block.    We
recommend moving this block and the preceding CSS link to the HEAD of your HTML
file. */</style><div id="mc_embed_signup"><form
action="//4pt0.us2.list-manage.com/subscribe/post?u=302452cbab507fde2dcba4705&amp;id=823a9e1e52"
method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form"
class="validate" target="_blank" novalidate>    <div
id="mc_embed_signup_scroll"> <h2>Subscribe to our mailing list</h2><div
class="indicates-required"><span class="asterisk">*</span> indicates
required</div><div class="mc-field-group"> <label for="mce-EMAIL">Email Address
<span class="asterisk">*</span></label> <input type="email" value=""
name="EMAIL" class="required email" id="mce-EMAIL"></div><div
class="mc-field-group"> <label for="mce-FNAME">First Name </label> <input
type="text" value="" name="FNAME" class="" id="mce-FNAME"></div><div
class="mc-field-group"> <label for="mce-LNAME">Last Name </label> <input
type="text" value="" name="LNAME" class="" id="mce-LNAME"></div><div
class="mc-field-group"> <label for="mce-MMERGE4">Zip Code <span
class="asterisk">*</span></label> <input type="text" value="" name="MMERGE4"
class="required" id="mce-MMERGE4"></div><div class="mc-field-group input-group">
    <strong>What kind of 4.0 Insider are you? You can be both! </strong>
    <ul><li><input type="checkbox" value="4" name="group[13989][4]"
id="mce-group[13989]-13989-0"><label for="mce-group[13989]-13989-0">I want
updates on what's going on in the 4.0 Community (jobs, events, big
ideas)</label></li><li><input type="checkbox" value="8" name="group[13989][8]"
id="mce-group[13989]-13989-1"><label for="mce-group[13989]-13989-1">I have an
idea I'm working on and want to get tips and tools for launching</label></li>
</ul></div><div class="mc-field-group input-group">    <strong>If you're working
on an idea, tell us what kind: </strong>    <ul><li><input type="checkbox"
value="16" name="group[13993][16]" id="mce-group[13993]-13993-0"><label
for="mce-group[13993]-13993-0">School</label></li><li><input type="checkbox"
value="32" name="group[13993][32]" id="mce-group[13993]-13993-1"><label
for="mce-group[13993]-13993-1">EdTech</label></li><li><input type="checkbox"
value="64" name="group[13993][64]" id="mce-group[13993]-13993-2"><label
for="mce-group[13993]-13993-2">Program or Service</label></li><li><input
type="checkbox" value="128" name="group[13993][128]"
id="mce-group[13993]-13993-3"><label
for="mce-group[13993]-13993-3">Other</label></li></ul></div> <div
id="mce-responses" class="clear">  <div class="response" id="mce-error-response"
style="display:none"></div>  <div class="response" id="mce-success-response"
style="display:none"></div> </div>     <div
style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text"
name="b_302452cbab507fde2dcba4705_823a9e1e52" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe"
id="mc-embedded-subscribe" class="button"></div>    </div></form></div><script
type='text/javascript'
src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script
type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes
= new
Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';fnames[4]='MMERGE4';ftypes[4]='text';fnames[3]='SIGNUP';ftypes[3]='text';fnames[5]='MMERGE5';ftypes[5]='text';fnames[6]='MMERGE6';ftypes[6]='text';fnames[7]='MMERGE7';ftypes[7]='text';fnames[8]='MMERGE8';ftypes[8]='text';}(jQuery));var
$mcj = jQuery.noConflict(true);</script>  





On Mon, Sep 4, 2017 4:04 PM, Blake Bertuccelli notifications@github.com  wrote:
@raphaelgang  - We'll need the HTML of a signup form. Here's Mailchimp's How-Tod
Document: 
https://kb.mailchimp.com/lists/signup-forms/add-a-signup-form-to-your-website

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.



Raphael Gang

504.512.0879 / @raphaelgang  / schedule a meeting  / subscribe to the 4.0
Newsletter  /
