### ISSUE TITLE
Update header & footer navigation with more traditional menu.

### ISSUE THREAD

**Issue by bbertucc** [4pt0/4pt0-theme#26]
Add traditional links to header and footer. Also, add social media buttons in footer.

For example, see: http://www.camelbackventures.org/

**Comment by bbertucc** [comment]
@raphaelgang - Let me know if you have any additional direction for the new navigation

**Comment by raphaelgang** [comment]
Just that we'd like it to show up as a hamburger menu on mobile, similar to camelback as well. we're ok with there being drop downs if needed as well.

**Comment by bbertucc** [comment]
How does this look? Any notes?
![screen-shot-2017-09-02-at-7 18 23-pm](https://user-images.githubusercontent.com/46652/29999612-f3de5b9e-9014-11e7-8e91-075243b761e5.jpg)

**Comment by raphaelgang** [comment]
Looks great. Thanks for making the change.

**Comment by raphaelgang** [comment]
Only question is about the logo on the left. There's a good amount of white there. Should the logo be a little larger?

**Comment by bbertucc** [comment]
Checkout the revised header and footer. The logo resizes to different display widths.

**Comment by raphaelgang** [comment]
Could you take Contact off the header? How do I edit it?
On the footer, the wording pushes right up against the edge of the page, too
much so.
Additionally, the header/footer look pretty off in mobile (chrome). Looks ok in
mobile safari, though the menu button at the top looks very cramped.  





On Mon, Sep 4, 2017 3:54 PM, Blake Bertuccelli notifications@github.com  wrote:
Closed #26.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.



Raphael Gang

504.512.0879 / @raphaelgang  / schedule a meeting  / subscribe to the 4.0
Newsletter  /

**Comment by bbertucc** [comment]
You can update the header and footer under the appearance tab. If you want
to change the text or update social links, you can click "Customizer". The
menus can be changed under the "Menus" link.
