### ISSUE TITLE
Image Sizing Oddities

### ISSUE THREAD

**Issue by bbertucc** [4pt0/4pt0-theme#45]
This issue will include all the image sizing oddities. If you see any oddities, reply with the following:

- Screenshot of image on page.
- URL of page.
- Brief description of why the image doesn't show up the way you want it.

After we have a good idea of the oddities, we're going to create formal image recommendations, that'll be posted to the repo's wiki.

Thanks y'all!

**Comment by bbertucc** [comment]
This image cuts off some of the heads in the mosaic. Page URL: http://4pt0.decubing.com/
![screen shot 2017-09-06 at 10 20 50 am](https://user-images.githubusercontent.com/46652/30119970-26258a48-92ed-11e7-94a6-2880fbb9b32c.png)

**Comment by bbertucc** [comment]
The mosaic photos can't be repositioned. This one gets cut off. Page URL: http://4pt0.decubing.com/

<img width="819" alt="screen shot 2017-09-06 at 5 16 50 pm" src="https://user-images.githubusercontent.com/46652/30137078-504d9f2e-9327-11e7-8844-c33006b61420.png">

**Comment by bbertucc** [comment]
@raphaelgang - Image Sizes are updated throughout the site. I added some in depth info on image sizes to the wiki: https://github.com/4pt0/4pt0-theme/wiki 

Additionally, you can set the focus are when adding any image. So, if you have a headless portrait, you can set the focal point to "Center Top".

Gonna close this issue, but feel free to re-open it if any images look odd.

**Comment by raphaelgang** [comment]
Hey Blake, I'm looking at the site and I'm still seeing the same issues with
the pictures. Am I missing something?  





On Thu, Sep 7, 2017 10:26 AM, Blake Bertuccelli notifications@github.com  wrote:
@raphaelgang  - Image Sizes are updated throughout the site. I added some in
depth info on image sizes to the wiki: https://github.com/4pt0/4pt0-theme/wiki

Additionally, you can set the focus are when adding any image. So, if you have a
headless portrait, you can set the focal point to "Center Top".

Gonna close this issue, but feel free to re-open it if any images look odd.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.



Raphael Gang

504.512.0879 / @raphaelgang  / schedule a meeting  / subscribe to the 4.0
Newsletter  /
